apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  namespace: roboshop  # <-- don't forget
  labels: 
    component: frontend
    project: roboshop
    tier: web
data: 
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log notice;
    pid /run/nginx.pid;

    include /usr/share/nginx/modules/*.conf;
  
    events {
        worker_connections 1024;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile            on;
        tcp_nopush          on;
        keepalive_timeout   65;
        types_hash_max_size 4096;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        include /etc/nginx/conf.d/*.conf;

        server {
            listen       8080;
            listen       [::]:80;
            server_name  _;
            root         /usr/share/nginx/html;

            include /etc/nginx/default.d/*.conf;

            error_page 404 /404.html;
            location = /404.html {
            }

            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
            }

            location /images/ {
              expires 5s;
              root   /usr/share/nginx/html;
              try_files $uri /images/placeholder.jpg;
            }
            location /api/catalogue/ { proxy_pass http://catalogue:8080/; }
            location /api/user/ { proxy_pass http://user:8080/; }
            location /api/cart/ { proxy_pass http://cart:8080/; }
            location /api/shipping/ { proxy_pass http://shipping:8080/; }
            #location /api/payment/ { proxy_pass http://payment:8080/; }

            location /health {
              stub_status on;
              access_log off;
            }

        }
    }

---
# 🔎 kubernetes Deployment
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  namespace: roboshop  # edi evvakapote default namespace lo run avutumdhi.
# deployment labels
  labels:
    component: frontend
    project: roboshop
    tier: web
spec:
  replicas: 1
# These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels: 
      component: frontend
      project: roboshop
      tier: web
# This is pod definition
  template:
    metadata:
      labels:
        component: frontend
        project: roboshop
        tier: web
    spec:
      containers: 
      - name: frontend
        image: kalyantalabothula/frontend:v1  # Mii Docker hub nimdi pull chesukuntumdhi, username,Password Evvakunda ante? --> Public image kabatti it will pull.
        volumeMounts:
          - name: nginx-conf # same name as to be 115 - 107 
            mountPath: /etc/nginx/nginx.conf # ee path loki below line 114 ni mount chestunna, readOnly: true petta
            subPath: nginx.conf
            readOnly: true
        # envFrom: 
        # - configMapRef:  
        #     name: frontend  
    volumes:  # <-- manam volume laga mention chesam, eppudu dhinini manam mount cheyali POD ki. 
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
# manam separate gha kuda configMap manifest.yaml file ni pettukovachhu, but manam GitBash lo everytime manam $ kubectl apply -f configmap.yaml ani evvali. ala evvakunda manam ela chesunnam. mottam okka manifest.yaml lo petti apply chestunnam. Like config.yaml ani, Deployment.yaml ani, service.yaml ani, 3 times avvali apply ani. Andhuke manam order lo petti estunnam. 
---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: roboshop   # <--
  labels:
    component: frontend
    project: roboshop
    tier: web
spec:
  type: LoadBalancer  # <---
  selector:
    component: frontend
    project: roboshop
    tier: web
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container Port 

# 🔎 system Port range ---> 0 to 1023
# The port numbers in the range from 0 to 1023 (0 to 210 − 1) are the well-known ports or system ports. These ports are Reserved for common and widely used services and protocols like HTTP(port 80), HTTPS(port 443), FTP(port 21), and DNS (port 53). They are tpically used by system processes or services. 


# So miru kubernetes environment lo Port: 80 ni Non-root container tho run cheste, Kubernetes dhaniki access evvadu. Root-Container tho run cheste dhaniki access estumdhi port:80 open cheyataniki. So manam Root-container ki veldhama ante vaddu. Simple port number change cheste set. So miru change cheali ante frontend lo nginx.conf lo listen ani untumdhi akkada change chesi RESART cheyali. 

# nginx conf as configmap 