apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  namespace: roboshop  # <-- don't forget
  labels: 
    component: frontend
    project: roboshop
    tier: web
data: 
   CART_ENDPOINT: "cart:8080"    # Remove equal symbol(=), and coloun symbol(:)
   DB_HOST: "mysql"
---
# 🔎 kubernetes Deployment
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  namespace: roboshop  # edi evvakapote default namespace lo run avutumdhi.
# deployment labels
  labels:
    component: frontend
    project: roboshop
    tier: web
spec:
  replicas: 1
# These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels: 
      component: frontend
      project: roboshop
      tier: web
# This is pod definition
  template:
    metadata:
      labels:
        component: frontend
        project: roboshop
        tier: web
    spec:
      containers: 
      - name: frontend
        image: kalyantalabothula/frontend:v1  # Mii Docker hub nimdi pull chesukuntumdhi, username,Password Evvakunda ante? --> Public image kabatti it will pull.  
        # envFrom: 
        # - configMapRef:  
        #     name: frontend   
# manam separate gha kuda configMap manifest.yaml file ni pettukovachhu, but manam GitBash lo everytime manam $ kubectl apply -f configmap.yaml ani evvali. ala evvakunda manam ela chesunnam. mottam okka manifest.yaml lo petti apply chestunnam. Like config.yaml ani, Deployment.yaml ani, service.yaml ani, 3 times avvali apply ani. Andhuke manam order lo petti estunnam. 
---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: roboshop   # <--
  labels:
    component: frontend
    project: roboshop
    tier: web
spec:
  type: LoadBalancer  # <---
  selector:
    component: frontend
    project: roboshop
    tier: web
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container Port 

# 🔎 system Port range ---> 0 to 1023
# The port numbers in the range from 0 to 1023 (0 to 210 − 1) are the well-known ports or system ports. These ports are Reserved for common and widely used services and protocols like HTTP(port 80), HTTPS(port 443), FTP(port 21), and DNS (port 53). They are tpically used by system processes or services. 


# So miru kubernetes environment lo Port: 80 ni Non-root container tho run cheste, Kubernetes dhaniki access evvadu. Root-Container tho run cheste dhaniki access estumdhi port:80 open cheyataniki. So manam Root-container ki veldhama ante vaddu. Simple port number change cheste set. So miru change cheali ante frontend lo nginx.conf lo listen ani untumdhi akkada change chesi RESART cheyali. 