# 🔎 kubernetes Deployment
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongodb
  namespace: roboshop
# deployment labels
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  replicas: 3
  selector:
    matchLabels: 
      project: roboshop
      environment: database
      app: mongodb
  template:
    metadata:
      labels:
        project: roboshop
        environment: database
        app: mongodb
    spec:
      containers: 
      - name: mongodb
        image: kalyantalabothula/mongodb
        ports:
        - containerPort: 80

