# 🔎 kubernetes Deployment
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis
  namespace: roboshop  # edi evvakapote default namespace lo run avutumdhi.
# deployment labels
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  replicas: 1
# These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels: 
      component: redis
      project: roboshop
      tier: database
# This is pod definition
  template:
    metadata:
      labels:
        component: redis
        project: roboshop
        tier: database
    spec:
      containers: 
      - name: redis
        image: redis:7.0 # Here redis is Public image, Mii Docker hub nimdi pull chesukuntumdhi
---
apiVersion: v1
kind: Service
metadata: 
  name: redis
  namespace: roboshop   # <---
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 6379 # service port
    targetPort: 6379 # container Port 